### ISSUE TITLE
Make Plugin multi-event compatible

### ISSUE THREAD

**Issue by jfwiebe** [jfwiebe/pretix-wp-plugin#1]
Currently, the plugin is only able to show the shop of one event within a WordPress instance. It would be great to have multiple shops within one site.

**Comment by raphaelm** [comment]
Thanks for making this! Yes, this would be great, as the widget is especially interesting for users with lots of events who have some kind of calendar on their website.

You could just reduce the settings to the JS and CSS links and have the event link as an argument to the shortcode, this would be an easy and powerful solution.

**Comment by jfwiebe** [comment]
@raphaelm That is a great idea!

Two questions came into my mind:
1. The CSS is event specific because of the event color, isn't it? I can not select another file for the `<head>` area because it is already processed before the shortcode is evaluated. 
2. The JS link is language-specific which should ideally be selected based on the viewers language but it is not clear which languages are supported by the event. Or: de-informal-JS-File is globally used, but one of the events has no de-informal texts, how to deal with that?

Do you have an idea for that?
Thanks & with best regards
JF

**Comment by raphaelm** [comment]
> The CSS is event specific because of the event color, isn't it? I can not select another file for the <head> area because it is already processed before the shortcode is evaluated.

Yes, it currently is only the color. I think it is fine if one needs to decide for one color for all widgets within one WordPress instance.

> Or: de-informal-JS-File is globally used, but one of the events has no de-informal texts, how to deal with that?

The built-in strings of the widget ("Add to cart") will still be de-informal, all other strings will be in any or the primary language of the event, I haven't tested it. I also think that is fine to have as collateral damage, if people really use events with different languages in their blog.

**Comment by jfwiebe** [comment]
implemented via 6b492bd and 0dd7494.
