### ISSUE TITLE
Embedding doesn't work

### ISSUE THREAD

**Issue by saschafoerster** [jfwiebe/pretix-wp-plugin#5]
I installed the plugin, created a shortcode and pretix was visible. But after loading I got an error (instead of the ticket shop:

```
[Error] Origin https://test.bonn.digital is not allowed by Access-Control-Allow-Origin.
[Error] Failed to load resource: Origin https://test.bonn.digital is not allowed by Access-Control-Allow-Origin. (product_list, line 0)
[Error] XMLHttpRequest cannot load https://ticket.bonn.digital/bonndigital/fuckupnights/widget/product_list?lang=de-informal due to access control checks.
[Error] 
```

I tried out different configurations of CORS in nginx, but didn't succed. Thanks for the plugin, and thanks for the help! 👍

**Comment by jfwiebe** [comment]
Hi @saschafoerster!

Thanks for your report! As I assume, your pretix instance is located at `https://ticket.bonn.digital` and the target page where the shop should be embedded is `https://test.bonn.digital`, right?

I assume that the ticket-server needs to respond with a header like `Access-Control-Allow-Origin: https://test.bonn.digital` as stated in this [Mozilla documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS).

If this is not the solution, it would be great if you could provide the two HTTP Request/Response Headers for `test.bonn.digital` and `ticket.bonn.digital`.

With best regards,
Jan Felix

**Comment by saschafoerster** [comment]
Somehow this problem got solved! So I will close it. (But I got a new one)
