### ISSUE TITLE
Add multi-events-support

### ISSUE THREAD

**Issue by saschafoerster** [jfwiebe/pretix-wp-plugin#6]
Fuckupnights are a row of events. (Veranstaltungsreihe). 

When I add the shortcode [pretix-widget eventurl="https://ticket.bonn.digital/bonndigital/fuckupnights/"] the shop isn't shown. 

When I add the shortcode [pretix-widget eventurl="https://ticket.bonn.digital/bonndigital/fuckupnights/2/"] (because it is the second event of the row) the show appears. 

When I put one ticket into the cart and want to continue I get this error message:
"No date was specified"
<img width="615" alt="bildschirmfoto 2017-11-09 um 21 17 53" src="https://user-images.githubusercontent.com/1153741/32627828-19b69340-c594-11e7-8fdf-427942068d4e.png">

**Comment by jfwiebe** [comment]
I am feeling like this is a problem of the pretix widget itself. I will have a try for it.

**Comment by jfwiebe** [comment]
Ah, for event rows the plugin needs to support another attribute. I'll implement it.

**Comment by jfwiebe** [comment]
Have a look at 772781a, you can now annotate the shortcode with a `subevent=2` attribute.

**Comment by saschafoerster** [comment]
Somehow it doesn't work. Some days ago, I didn't see anything. Now only "Gutscheine" are accepted, even though we are selling tickets on the original site. 
![bildschirmfoto 2017-11-28 um 13 48 54](https://user-images.githubusercontent.com/1153741/33320604-163fd376-d443-11e7-8130-8b7170fc799d.png)

**Comment by jfwiebe** [comment]
Hi!

Sorry, I was on vacation. Can you compare the HTML code displayed by the plugin to the code snippet that is displayed within pretix?

**Comment by saschafoerster** [comment]
As the event is over (for now) I can't really compare. But I will check it the next time. For single events it works though! I will close it and reopen if it doesn't work any other time. ;)
